version: 2.1
jobs:
  build:
    machine: true
    steps:
      ## install more recent version of docker-compose
       - run: |
           sudo DEBIAN_FRONTEND=noninteractive apt-get update
           sudo DEBIAN_FRONTEND=noninteractive apt-get install -y libffi-dev libssl-dev python3-dev python3-pyqt5 python3-pyqt5.qtwebengine python3 python3-pip
       - run: pip3 install docker-compose
       - run: sudo usermod -aG docker $USER
       ## setup only
       - checkout
       - run: cd ./docker && docker-compose up --exit-code-from zephyr-base
