version: 2.1
jobs:
 build:
   machine: true
   steps:
     ## install more recent version of docker-compose
     - run: sudo curl -L "https://github.com/docker/compose/releases/download/1.28.6/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
     - run: sudo chmod a+x /usr/local/bin/docker-compose

     ## setup only
     - checkout
     - run: cd ./docker && export ENV_UID="$(id -u)" && export ENV_GID="$(id -g)" && export ENV_USER="$(whoami)" && docker-compose up --exit-code-from zephyr-base
