version: '3.8'

services:
    zephyr:
        container_name: zephyr
        image: ${USER}/zephyr:DEVEL
        build:
            context: build_context
            dockerfile: Dockerfile
            args:
                USER: "${USER}"
                UID: "${UID}"
                GID: "${GID}"
        user: "${UID}:${GID}"     ## docker run --user=${USER}
        stdin_open: true          ## docker run -i
        tty: true                 ## docker run -t
        privileged: true
        environment:
          - USER
          - DISPLAY=$DISPLAY
        env_file:
          - .env
        group_add:
          - 20                    ## group: dialout
        volumes:
          ## x11 access
          - /tmp/.X11-unix:/tmp/.X11-unix
          - ~/.Xauthority:/root/.Xauthority
          ## folder must be around
          - type: bind
            source: ~/.ssh
            target: /home/${USER}/.ssh
          - type: bind
            source: ./build_configs
            target: /home/$USER/configs
          ## folders not need to be around
          - ./zephyrproject:/home/${USER}/zephyrproject
        network_mode: "host"     ## needed for x11 forwarding
