version: '3.8'

services:
    zephyr-base:
        container_name: zephyr-base
        image: ${USER}/zephyr-base:20211101
        build:
            context: build_context
            dockerfile: Dockerfile
            args:
                USER: "${USER}"
                UID: "${UID}"
                GID: "${GID}"
        user: "${UID}:${GID}"
        stdin_open: true          ## docker run -i
        tty: true                 ## docker run -t
        privileged: true
        environment:
          - USER
        env_file:
          - .env
        volumes:
          ## folder must be around
          - type: bind
            source: ~/.ssh
            target: /home/${USER}/.ssh
          - type: bind
            source: ./build_configs
            target: /home/$USER/configs
          ## folders not need to be around
          - ~/.gitconfig:/home/$USER/.gitconfig:ro
          - ./zephyrproject:/home/${USER}/zephyrproject
